version: "3.8"

services:
  spark-master:
    build: .
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MASTER_HOST=spark-master
    command: >
      bash -c "
      /opt/spark/sbin/start-master.sh &&
      tail -f /opt/spark/logs/*"
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ../:/app

  spark-worker-1:
    build: .
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*"
    ports:
      - "8081:8081"
    volumes:
      - ../:/app

  spark-worker-2:
    build: .
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*"
    ports:
      - "8082:8081"
    volumes:
      - ../:/app

#   postgres:
#     image: postgres:15
#     container_name: postgres
#     environment:
#       POSTGRES_DB: warehouse
#       POSTGRES_USER: spark
#       POSTGRES_PASSWORD: spark
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
